name:                DeliveryEstimate
version:             0.1.0.0
github:              "githubuser/DeliveryEstimate"
license:             BSD3
author:              "Adam"
maintainer:          "noemail@nodomain.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DeliveryEstimate#readme>

dependencies:
- base >= 4.7 && < 5
- wreq >= 0.5.2.1
- lens >= 4.18.1
- split >= 0.2.3.3
- text
- bytestring

library:
  source-dirs: src

executables:
  DeliveryEstimate-exe:
    main:                DeliveryEst.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DeliveryEstimate

tests:
  DeliveryEstimate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DeliveryEstimate
